name: studaai

services:
  database:
    image: bitnami/postgresql:16
    container_name: studaai_db
    restart: always
    environment:
      - POSTGRESQL_USERNAME=studaai
      - POSTGRESQL_PASSWORD=studaai
      - POSTGRESQL_DATABASE=studaai_db
    ports:
      - 5432:5432
    volumes:
      - db_data:/bitnami/postgresql

volumes:
  db_data:
