import {
  ArrowRight,
  BellIcon,
  Book,
  ChevronDown,
  CreditCard,
  EllipsisVertical,
  Home,
  Laptop,
  Loader,
  LogOut,
  MoonStar,
  Plus,
  Settings2,
  SmartphoneCharging,
  SquareCheck,
  SquarePen,
  Stars,
  Sun,
  Trash2,
  User,
  X,
  type LucideProps,
} from "lucide-react";

import { GitHub } from "./github";
import { Google } from "./google";

export type IconProps = LucideProps;

export const Icons = {
  github: GitHub,
  google: Google,
  loader: Loader,
  home: Home,
  settings: Settings2,
  bell: BellIcon,
  user: User,
  logout: LogOut,
  book: Book,
  flashcard: SmartphoneCharging,
  quiz: SquareCheck,
  credit: CreditCard,
  sun: Sun,
  moon: MoonStar,
  desktop: Laptop,
  edit: SquarePen,
  close: X,
  trash: Trash2,
  dots: EllipsisVertical,
  add: Plus,
  stars: Stars,
  arrowRight: ArrowRight,
  chevronDown: ChevronDown,
};
